[project]
name = "production-ready-ds"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "davidkasdas", email = "david.kasdas@hotmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "colorlog>=6.12.0",
    "hydra-core>=1.3.5",
    "jupyterlab>=4.6.3",
    "loguru>=0.7.3",
    "mypy>=2.3.0",
    "numpy>=2.5.1",
    "pandas>=3.0.5",
    "pandera>=0.32.1",
    "pydantic>=2.13.4",
    "scikit-learn>=1.9.0",
    "textblob>=0.20.1",
]

[project.scripts]
production-ready-ds = "production_ready_ds:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pre-commit>=4.6.1",
    "pytest>=9.1.1",
]
